{
 "title": "Cassandra Dashboard",
 "description": "Contribution from Ahmed Eljami",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "filter",
    "label": "Filter",
    "query": "cassandra_table_operation_latency_seconds_count"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values($filter,cassandra_cluster)"
   },
   {
    "name": "dc",
    "label": "Datacenter",
    "query": "label_values($filter{cassandra_cluster=~\"$cluster\"}, cassandra_datacenter)"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "label_values($filter{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\"}, cassandra_rack)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values($filter{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\"}, instance)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values($filter{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\"}, keyspace)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values($filter{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\"}, table)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Down",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "topk (1, cassandra_endpoint_active{cassandra_cluster=~\"$cluster\"} < 1) by(exported_endpoint)\n",
     "legendFormat": "{{exported_endpoint}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Reads/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\", operation=\"read\"}[5m]))"
    }
   ]
  },
  {
   "title": "Writes/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\", operation=\"write\"}[5m]))"
    }
   ]
  },
  {
   "title": "Compaction Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_compaction_completed_tasks_total{cassandra_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Client Req TimeOut",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_client_request_timeouts_total{cassandra_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "GC Last Collection Duration Health",
   "type": "grafana-polystat-panel",
   "description": "Thresholds can be adjusted according to your needs.\nDefault values: 250ms for Warning, 500ms for Critical",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "cassandra_jvm_gc_last_collection_duration_seconds{cassandra_cluster=~\"$cluster\",collector=\"G1 Young Generation\"}",
     "legendFormat": "{{instance}} G1 Young"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_dropped_messages_total{cassandra_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Hints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(irate(cassandra_storage_hints_total{cassandra_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(cassandra_client_native_connections{cassandra_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Client Request Failures",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by(cassandra_cluster) (irate(cassandra_client_request_failures_total{cassandra_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Nodes CPU Health (used by cassandra)",
   "type": "grafana-polystat-panel",
   "description": "Thresholds can be adjusted according to your needs:\nDefault values: 60% Warning. 80% Critical",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cassandra_process_recent_cpu_load_ratio{cassandra_cluster=\"$cluster\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Global Data Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(cassandra_table_live_disk_space_bytes{cassandra_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Native Active Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_thread_pool_completed_tasks_total{cassandra_cluster=~\"$cluster\",pool=\"Native-Transport-Requests\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Native Blocked Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(cassandra_thread_pool_blocked_tasks{pool=\"Native-Transport-Requests\",cassandra_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Used",
   "type": "grafana-polystat-panel",
   "description": "Thresholds can be adjusted according to your needs.\nDefault values: 75% for Warning, 90% for Critical",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 9 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "((sum by (instance) (cassandra_jvm_memory_pool_used_bytes{cassandra_cluster=\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}  > 0)\n/\n(sum by (instance) (cassandra_jvm_memory_pool_maximum_bytes{cassandra_cluster=\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}  > 0)))) \n* 100",
     "legendFormat": "{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "AVG Read Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate(cassandra_client_request_latency_seconds_sum{cassandra_cluster=~\"$cluster\",operation=\"read\"}[5m])) by (cassandra_cluster)\n\t/\n\tsum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=~\"$cluster\",operation=\"read\"}[5m])) by (cassandra_cluster)"
    }
   ]
  },
  {
   "title": "Total Reads/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\", operation=\"read\"}[5m]))",
     "legendFormat": "Total Reads/s"
    }
   ]
  },
  {
   "title": "Nodes Compactions Health",
   "type": "grafana-polystat-panel",
   "description": "Thresholds can be adjusted according to your needs.\nDefault values: 40 for Warning, 70 for Critical",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(cassandra_compaction_completed_total{cassandra_cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AVG Write Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\tsum (irate(cassandra_client_request_latency_seconds_sum{cassandra_cluster=~\"$cluster\",operation=\"write\"}[5m])) by (cassandra_cluster)/\n\tsum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=~\"$cluster\",operation=\"write\"}[5m])) by (cassandra_cluster)"
    }
   ]
  },
  {
   "title": "Total Writes/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (cassandra_cluster)(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\", operation=\"write\"}[5m]))",
     "legendFormat": "Total Writes/s"
    }
   ]
  },
  {
   "title": "Node Metrics (No Keyspace/Table Filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Reads/s",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (cassandra_cluster,instance) (irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\", operation=\"read\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Writes/s",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum by (cassandra_cluster,instance) (irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\", operation=\"write\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AVG Client Read Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(cassandra_client_request_latency_seconds_sum{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"read\",instance=~\"$host\"}[5m]))\n/\nsum by (instance) (irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"read\",instance=~\"$host\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AVG Client Write Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(cassandra_client_request_latency_seconds_sum{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"write\",instance=~\"$host\"}[5m]))\n/\nsum by (instance) (irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"write\",instance=~\"$host\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Clients Connected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "cassandra_client_native_connections{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Clients Request TimeOut",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_client_request_timeouts_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\",consistency=\"LOCAL_ONE\"}[5m])",
       "legendFormat": "{{instance}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Node Clients Request Failure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_client_request_failures_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\",consistency=\"LOCAL_ONE\"}[5m])",
       "legendFormat": "{{instance}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Compactions Completed Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_compaction_completed_tasks_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}[5m])",
       "legendFormat": "{{instance}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Total Hint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_storage_hints_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(cassandra_dropped_messages_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Space Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (cassandra_table_live_disk_space_bytes{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics (With Keyspace/Table Filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Read Count Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\", operation=\"read\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Write Count Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\", operation=\"write\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table AVG Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_operation_latency_seconds_sum{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"read\",instance=~\"$host\", table=~\"$table\"}[5m])\n/\nirate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"read\",instance=~\"$host\", table=~\"$table\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table AVG Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_operation_latency_seconds_sum{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"write\",instance=~\"$host\", table=~\"$table\"}[5m])/irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",operation=\"write\",instance=~\"$host\", table=~\"$table\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Disk Space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_disk_space_bytes{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Dropped Mutation ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_dropped_mutations_total{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Partition Size Maximum",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_partition_size_maximum_bytes{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Speculative Retries Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_speculative_retries_total{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Sstables Per Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_sstables_per_read_count{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Tombstones Scanned",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "irate(cassandra_table_tombstones_scanned_count{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}[5m])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Pending Flushes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_pending_flushes{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Live Sstables",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_live_sstables{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Live Rows Scanned",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_live_rows_scanned{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Estimated Partitions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_estimated_partitions{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    },
    {
     "title": "Table Estimated Pending Compactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host $tag_keyspace $tag_scope",
       "expr": "cassandra_table_estimated_pending_compactions{cassandra_cluster=~\"$cluster\", cassandra_datacenter=~\"$dc\", cassandra_rack=~\"$rack\", instance=~\"$host\", keyspace=~\"$keyspace\", table=~\"$table\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "keyspace" ], "type": "tag" },
        { "params": [ "scope" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} {{keyspace}} {{table}}",
       "measurement": "cassandra_ColumnFamily",
       "select": [
        [
         { "params": [ "ReadLatency_Count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dc", "operator": "=~", "value": "/^$dc$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "keyspace", "operator": "=~", "value": "/^$keyspace$/" },
        { "condition": "AND", "key": "scope", "operator": "=~", "value": "/^$columnfamily$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics By Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Young Gen - Number Of collections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_jvm_gc_collection_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\",collector=\"G1 Young Generation\"}[5m])",
       "legendFormat": "{{instance}} Young Gen"
      }
     ]
    },
    {
     "title": "Young Gen Collection Duration ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_jvm_gc_estimated_collection_duration_seconds_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\",collector=\"G1 Young Generation\"}[5m])",
       "legendFormat": "{{instance}} Young Gen"
      }
     ]
    },
    {
     "title": "Old Gen - Number Of collections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_jvm_gc_collection_count{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\",collector=\"G1 Old Generation\"}[5m])",
       "legendFormat": "{{instance}} Old Gen"
      }
     ]
    },
    {
     "title": "Old Gen Collection Duration ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_jvm_gc_estimated_collection_duration_seconds_total{cassandra_cluster=~\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\",collector=\"G1 Old Generation\"}[5m])",
       "legendFormat": "{{instance}} Old Gen"
      }
     ]
    },
    {
     "title": "Memory Pool Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((sum by (instance) (cassandra_jvm_memory_pool_used_bytes{cassandra_cluster=\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}  > 0)\n/\n(sum by (instance) (cassandra_jvm_memory_pool_maximum_bytes{cassandra_cluster=\"$cluster\",cassandra_datacenter=~\"$dc\",cassandra_rack=~\"$rack\",instance=~\"$host\"}  > 0)))) \n* 100",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}