apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multicasskops.db.orange.com
  labels:
    app: {{ template "multi-casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: db.orange.com
  names:
    kind: MultiCasskop
    listKind: MultiCasskopList
    plural: multicasskops
    singular: multicasskop
  scope: Namespaced
  version: v1alpha1
