apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "multi-casskop.fullname" . }}
  labels:
    app: {{ template "multi-casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: cassandra
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "multi-casskop.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "multi-casskop.name" . }}
        app: {{ template "multi-casskop.name" . }}
        operator: {{ template "multi-casskop.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets.name }}
{{- end }}
{{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "multi-casskop.name" . }}
{{- end }}
      securityContext:
        runAsUser: 1000
      containers:
      - name: {{ template "multi-casskop.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
{{- if .Values.command }}
        command:
          - {{ .Values.command }}
{{- end }}
        args:
          - {{ .Values.k8s.local }}
{{- range .Values.k8s.remote }}
          - {{ . }}
{{- end }}
        readinessProbe:
          exec:
            command:
              - /health
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "multi-casskop"
{{- if .Values.debug.enable }}
          - name: LOG_LEVEL
            value: Debug
{{- end }}
        volumeMounts:
{{- range .Values.k8s.remote }}
        - mountPath: /var/run/secrets/admiralty.io/serviceaccountimports/{{ . }}
          name: {{ . }}
          readOnly: true
{{- end }}
      volumes:
{{- range .Values.k8s.remote }}
      - name: {{ . }}
        secret:
          defaultMode: 420
          secretName: {{ . }}
{{- end }}

