{{- if .Values.rbacEnable }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "multi-casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "multi-casskop.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "multi-casskop.name" . }}
roleRef:
  kind: Role
  name: {{ template "multi-casskop.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
