kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: casskop
subjects:
- kind: ServiceAccount
  name: casskop
roleRef:
  kind: Role
  name: casskop
  apiGroup: rbac.authorization.k8s.io
