apiVersion: v1
kind: Secret
metadata:
  name: jolokia-auth
type: Opaque
data:
  password: TTBucDQ1NXcwcmQ=
  username: am9sb2tpYS11c2Vy
---
apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
  labels:
    cluster: k8s.kaas
spec:
  baseImage: orangeopensource/cassandra-image
  #version: 3.11.4-8u212-0.3.1-cqlsh
  version: latest-cqlsh
  configMapName: cassandra-configmap-v1
  dataCapacity: "20Gi"
  dataStorageClass: "standard-wait"
  imagepullpolicy: IfNotPresent
  imageJolokiaSecret:
    name: jolokia-auth
  checkStatefulsetsAreEqual: true
  hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: true
  maxPodUnavailable: 1
  runAsUser: 1000
  resources:         
    requests:
      cpu: '1'
      memory: 2Gi
    limits:
      cpu: '1'
      memory: 2Gi
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        numTokens: 256
        labels: 
          failure-domain.beta.kubernetes.io/region: europe-west1
        rack:
          - name: rack1
            labels:
              failure-domain.beta.kubernetes.io/zone: europe-west1-b
          - name: rack2
            labels:
              failure-domain.beta.kubernetes.io/zone: europe-west1-c
          - name: rack3
            labels:
              failure-domain.beta.kubernetes.io/zone: europe-west1-d
#UNCOMMENT FOR DEMO
#      - name: dc2
#        nodesPerRacks: 1
#        numTokens: 256
#        labels: 
#          failure-domain.beta.kubernetes.io/region: europe-west1
#        rack:
#          - name: rack1
#            labels:
#              failure-domain.beta.kubernetes.io/zone: europe-west1-b
#          - name: rack2
#            labels:
#              failure-domain.beta.kubernetes.io/zone: europe-west1-c
#          - name: rack3
#            labels:
#              failure-domain.beta.kubernetes.io/zone: europe-west1-d
#
