apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
spec:
  nodesPerRacks: 3
  cassandraImage: cassandra:3.11
  #configMapName: cassandra-jvm-configmap-full
  #imagePullSecret:
  #  name: advisedev # To authenticate on docker registry
  rollingPartition: 0
  imagePullPolicy: "IfNotPresent"
  dataCapacity: "1Gi"
  dataStorageClass: "local-storage"
  hardAntiAffinity: false
  deletePVC: true
  autoPilot: true
  autoUpdateSeedList: false
  resources:         
    requests:
      cpu: '512m'
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 1Gi
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1
