apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multicasskops.db.orange.com
spec:
  group: db.orange.com
  names:
    kind: MultiCasskop
    listKind: MultiCasskopList
    plural: multicasskops
    singular: multicasskop
  scope: Namespaced
  subresources:
    status: {}
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
