## Cassandra Operator Image
##
image:
  repository: orangeopensource/multi-casskop
  tag: 0.0.1-multi-cluster
#  tag: 0.0.1-hbx-multi-cluster
  pullPolicy: Always
  imagePullSecrets:
    enabled: false

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 1
    memory: 512Mi

## If true, create & deploy the CRD
##
createCustomResource: true

## If true, create & use RBAC resources
##
rbacEnable: true

## if true deploy service for metrics access
metricService: false

debug:
  enabled: false

command: /usr/local/bin/multi-casskop
args:
  - rickaastley-sph
  - rickaastley-bgl
