apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "cassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "cassandra-operator.name" . }}
{{- range .Values.clusterServiceAccountsName }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "cassandra-operator.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  name: {{ . }}
{{- end }}