//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2

import (
	apiv2 "github.com/Orange-OpenSource/casskop/api/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiCasskop) DeepCopyInto(out *MultiCasskop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiCasskop.
func (in *MultiCasskop) DeepCopy() *MultiCasskop {
	if in == nil {
		return nil
	}
	out := new(MultiCasskop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiCasskop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiCasskopList) DeepCopyInto(out *MultiCasskopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiCasskop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiCasskopList.
func (in *MultiCasskopList) DeepCopy() *MultiCasskopList {
	if in == nil {
		return nil
	}
	out := new(MultiCasskopList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiCasskopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiCasskopSpec) DeepCopyInto(out *MultiCasskopSpec) {
	*out = *in
	if in.DeleteCassandraCluster != nil {
		in, out := &in.DeleteCassandraCluster, &out.DeleteCassandraCluster
		*out = new(bool)
		**out = **in
	}
	in.Base.DeepCopyInto(&out.Base)
	if in.Override != nil {
		in, out := &in.Override, &out.Override
		*out = make(map[string]apiv2.CassandraCluster, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiCasskopSpec.
func (in *MultiCasskopSpec) DeepCopy() *MultiCasskopSpec {
	if in == nil {
		return nil
	}
	out := new(MultiCasskopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiCasskopStatus) DeepCopyInto(out *MultiCasskopStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiCasskopStatus.
func (in *MultiCasskopStatus) DeepCopy() *MultiCasskopStatus {
	if in == nil {
		return nil
	}
	out := new(MultiCasskopStatus)
	in.DeepCopyInto(out)
	return out
}
